# These are supported funding model platforms

github: [nc1BitW]
patreon: nc1BitW
custom: ["bitcoin:3Has7zwrLiTwmufjeuexUBUNQHhGQUhUJB?label=Bitwanga&message=https%3A%2F%2Fgithub.com%2Fnc1BitW%2FBitWanga-public%2Fedit%2Fmaster%2FREADME.md"]
community_bridge: BitWanga-public
issuehunt: https://issuehunt.io/r/nc1BitW/BitWanga-public
